<a href="https://colab.research.google.com/github/surimajain/QuantAnalytics/blob/main/Historical_Data_Extraction_and_simulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install yfinance

Collecting yfinance
  Downloading https://files.pythonhosted.org/packages/a7/ee/315752b9ef281ba83c62aa7ec2e2074f85223da6e7e74efb4d3e11c0f510/yfinance-0.1.59.tar.gz
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.9)
Collecting lxml>=4.5.1
  Downloading https://files.pythonhosted.org/packages/30/c0/d0526314971fc661b083ab135747dc68446a3022686da8c16d25fcf6ef07/lxml-4.6.3-cp37-cp37m-manylinux2014_x86_64.whl (6.3MB)
     |████████████████████████████████| 6.3MB 41.4MB/s
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Building wheels for collected packages: yfinance
  Building wheel for yfinance (setup.py) ... done
  Created wheel for yfinance: filename=yfinance-0.1.59-py2.py3-none-any.whl size=23455 sha256=06d5392dd5a0de7dbfa6c3ca983293dc9c27369689a01c87acf4c76ff46c71c5
  Stored in directory: /root/.cache/pip/wheels/f8/2a/0f/4b5a86e1d52e451757eb6bc17fd899629f0925c777741b6d04
Successfully built yfinance
Installing collected packages: lxml, yfinance
  Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
Successfully installed lxml-4.6.3 yfinance-0.1.59

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [4]:
# stocks=['AAPL','IBM','MSFT']
stocks=['MSFT','VOW3','ADS.DE','AAPL','IBM']
df_three_Stocks = yf.download(tickers = stocks,start = "2016-04-01",end = "2021-03-31",)

[*********************100%***********************]  3 of 3 completed

1 Failed download:
- VOW3: No data found, symbol may be delisted

In [5]:
df_three_Stocks.head()

                     Adj Close                  ...    Volume
                        ADS.DE       MSFT VOW3  ...    ADS.DE        MSFT VOW3
Date                                            ...
2016-04-01 00:00:00  92.990936  50.838734  NaN  ...  589447.0  24399200.0  NaN
2016-04-04 00:00:00  94.261688  50.710655  NaN  ...  512238.0  18928800.0  NaN
2016-04-05 00:00:00  93.263245  49.914726  NaN  ...  616977.0  19272300.0  NaN
2016-04-06 00:00:00  94.488609  50.427040  NaN  ...  514152.0  21188700.0  NaN
2016-04-07 00:00:00  93.580933  49.823242  NaN  ...  584383.0  19225100.0  NaN

[5 rows x 18 columns]

In [6]:
df_three_Stocks.columns

MultiIndex([('Adj Close', 'ADS.DE'),
            ('Adj Close',   'MSFT'),
            ('Adj Close',   'VOW3'),
            (    'Close', 'ADS.DE'),
            (    'Close',   'MSFT'),
            (    'Close',   'VOW3'),
            (     'High', 'ADS.DE'),
            (     'High',   'MSFT'),
            (     'High',   'VOW3'),
            (      'Low', 'ADS.DE'),
            (      'Low',   'MSFT'),
            (      'Low',   'VOW3'),
            (     'Open', 'ADS.DE'),
            (     'Open',   'MSFT'),
            (     'Open',   'VOW3'),
            (   'Volume', 'ADS.DE'),
            (   'Volume',   'MSFT'),
            (   'Volume',   'VOW3')],
           )

In [7]:
df=pd.DataFrame(columns=['Adj Close',	'Close',	'High',	'Low',	'Open','Volume','Ticker','Date'])
for stock in stocks:
  df_stock=yf.download(tickers = stock,start = "2016-04-01",end = "2021-03-31",)
  df_stock['Ticker']=stock
  df_stock['IDENTIFIER_TYP']='INHOUSE'
  df_stock['Date']=df_stock.index
  df_stock['INSTRUMENT_TYPE']='EQSHR'
  df_stock['PRICE_CURRENCY']='USD'
  df=df.append(df_stock)
df.reset_index(drop=True,inplace=True)
df_new=df[['Ticker','Date','Adj Close',	'Close',	'High',	'Low',	'Open','Volume']]
df_new.to_csv("/content/sample_data/equities.csv")
df
# (IDENTIFIER_TYPE,INSTRUMENT_IDENTIFIER,INSTRUMENT_TYPE,PRICE_CURRENCY,PRICE_DATE_YYYYMMDD,UNIT_PRICE,PRICE_TYPE,MARKET_IDENTIFIER_TYPE,MARKET_IDENTIFIER,ADDITIONAL_PRICE_QUALIFIER,DATA_SOURCE_ID,PRICE_SOURCE,DOWNSTREAM_SYSTEM,PRICING_METHOD,PRICE_QUOTE_METHOD,COMMENTS,Open,Ask,Bid,Close,High,Low,Mid,Last
# INHOUSE,Apple Inc,EQSHR,USD,20191129,66.81,CLOSE,MIC,XNAS,,,,SS_DWDF,,,EQSHR from Investing,66.65,67.0,66.47,66.81,67.0,66.47,66.735,66.81

# )

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- VOW3: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed

       Adj Close       Close  ...  INSTRUMENT_TYPE  PRICE_CURRENCY
0      50.838734   55.570000  ...            EQSHR             USD
1      50.710655   55.430000  ...            EQSHR             USD
2      49.914726   54.560001  ...            EQSHR             USD
3      50.427040   55.119999  ...            EQSHR             USD
4      49.823242   54.459999  ...            EQSHR             USD
...          ...         ...  ...              ...             ...
2520  275.881134  278.799988  ...            EQSHR             USD
2521  259.059113  261.799988  ...            EQSHR             USD
2522  258.960175  261.700012  ...            EQSHR             USD
2523  261.335052  264.100006  ...            EQSHR             USD
2524  262.225616  265.000000  ...            EQSHR             USD

[2525 rows x 11 columns]

In [8]:
yf.Ticker('AAPL').info#.get('Currency')

{'52WeekChange': 0.44683027,
 'SandP52WeekChange': 0.35929394,
 'address1': 'One Apple Park Way',
 'algorithm': None,
 'annualHoldingsTurnover': None,
 'annualReportExpenseRatio': None,
 'ask': 130.4,
 'askSize': 1000,
 'averageDailyVolume10Day': 65388200,
 'averageVolume': 88994153,
 'averageVolume10days': 65388200,
 'beta': 1.208152,
 'beta3Year': None,
 'bid': 130.33,
 'bidSize': 1400,
 'bookValue': 4.146,
 'category': None,
 'circulatingSupply': None,
 'city': 'Cupertino',
 'companyOfficers': [],
 'country': 'United States',
 'currency': 'USD',
 'dateShortInterest': 1622160000,
 'dayHigh': 130.49,
 'dayLow': 127.07,
 'dividendRate': 0.88,
 'dividendYield': 0.0067000003,
 'earningsQuarterlyGrowth': 1.101,
 'enterpriseToEbitda': 22.464,
 'enterpriseToRevenue': 6.891,
 'enterpriseValue': 2242313191424,
 'exDividendDate': 1620345600,
 'exchange': 'NMS',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'expireDate': None,
 'fiftyDayAverage': 127.50912,
 'fiftyTwoWeekHigh': 145.09,
 'fiftyTwoWeekLow': 86.18,
 'fiveYearAverageReturn': None,
 'fiveYearAvgDividendYield': 1.34,
 'floatShares': 16670609616,
 'forwardEps': 5.35,
 'forwardPE': 24.388784,
 'fromCurrency': None,
 'fullTimeEmployees': 100000,
 'fundFamily': None,
 'fundInceptionDate': None,
 'gmtOffSetMilliseconds': '-14400000',
 'heldPercentInsiders': 0.00066,
 'heldPercentInstitutions': 0.58689,
 'impliedSharesOutstanding': None,
 'industry': 'Consumer Electronics',
 'isEsgPopulated': False,
 'lastCapGain': None,
 'lastDividendDate': 1620345600,
 'lastDividendValue': 0.22,
 'lastFiscalYearEnd': 1601078400,
 'lastMarket': None,
 'lastSplitDate': 1598832000,
 'lastSplitFactor': '4:1',
 'legalType': None,
 'logo_url': 'https://logo.clearbit.com/apple.com',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
 'longName': 'Apple Inc.',
 'market': 'us_market',
 'marketCap': 2177397948416,
 'maxAge': 1,
 'maxSupply': None,
 'messageBoardId': 'finmb_24937',
 'morningStarOverallRating': None,
 'morningStarRiskRating': None,
 'mostRecentQuarter': 1616803200,
 'navPrice': None,
 'netIncomeToCommon': 76311003136,
 'nextFiscalYearEnd': 1664150400,
 'open': 127.82,
 'openInterest': None,
 'payoutRatio': 0.1834,
 'pegRatio': 1.45,
 'phone': '408-996-1010',
 'previousClose': 127.35,
 'priceHint': 2,
 'priceToBook': 31.471298,
 'priceToSalesTrailing12Months': 6.691327,
 'profitMargins': 0.23451,
 'quoteType': 'EQUITY',
 'regularMarketDayHigh': 130.49,
 'regularMarketDayLow': 127.07,
 'regularMarketOpen': 127.82,
 'regularMarketPreviousClose': 127.35,
 'regularMarketPrice': 130.48,
 'regularMarketVolume': 96906490,
 'revenueQuarterlyGrowth': None,
 'sector': 'Technology',
 'sharesOutstanding': 16687599616,
 'sharesPercentSharesOut': 0.0074,
 'sharesShort': 123121920,
 'sharesShortPreviousMonthDate': 1619740800,
 'sharesShortPriorMonth': 82710348,
 'shortName': 'Apple Inc.',
 'shortPercentOfFloat': 0.0074,
 'shortRatio': 1.36,
 'startDate': None,
 'state': 'CA',
 'strikePrice': None,
 'symbol': 'AAPL',
 'threeYearAverageReturn': None,
 'toCurrency': None,
 'totalAssets': None,
 'tradeable': False,
 'trailingAnnualDividendRate': 0.82,
 'trailingAnnualDividendYield': 0.0064389477,
 'trailingEps': 4.449,
 'trailingPE': 29.327938,
 'twoHundredDayAverage': 128.16014,
 'volume': 96906490,
 'volume24Hr': None,
 'volumeAllCurrencies': None,
 'website': 'http://www.apple.com',
 'yield': None,
 'ytdReturn': None,
 'zip': '95014'}